name: Rust Test and Benchmark

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          # Use a stable cache key for consistent caching across jobs
          shared-key: "orbit-rust-cache"
          # Cache both debug and release target directories
          cache-targets: "true"

      - name: Check compilation
        run: cargo check --message-format=short

      - name: Run unit tests
        run: cargo test --message-format=short
